import Joi from "joi";

const CategoryValidationSchema = Joi.object({
    tenantId: Joi.string()
        .guid({ version: ["uuidv4"] })
        .optional() // auto-generated by default
        .messages({
          "string.guid": "tenantId must be a valid UUID v4",
        }),
    type : Joi.string().equal('Parent').required().message({"provided Type is invalid"})
})