import Joi from "joi";

const CategoryValidationSchema = Joi.object({
    tenantId: Joi.string()
        .guid({ version: ["uuidv4"] })
        .optional() // auto-generated by default
        .messages({
            "string.guid": "tenantId must be a valid UUID v4",
        }),
    type: Joi.string().equal('Child').required().message({ "string.equal": "provided Type is invalid" }),
    centralStatus: Joi.string()
        .valid("active", "inactive")
        .default("active")
        .optional()
        .messages({
            "any.only": "centralStatus must be either 'active' or 'inactive'",
        }),

    status: Joi.string().valid("active", "inactive").default("active").optional().message({ "any.only": "Status must be either 'active' or 'inactive'" }),
    name: Joi.object({
        en: Joi.string().trim().optional().messages({
            "string.base": "English name must be a string",
        }),
        ar: Joi.string().trim().optional().messages({
            "string.base": "Arabic name must be a string",
        }),
    }).optional(),
    slug: Joi.string().trim().required().messages({
        "string.base": "Slug must be a string",
        "string.empty": "Slug cannot be empty",
        "any.required": "Slug is a required field",
    }),
    profileImage: Joi.string().uri().optional().messages({
        "string.base": "Profile image must be a valid string path or URL",
        "string.uri": "Profile image must be a valid URI",
    }),
    coverImage: Joi.string().uri().optional().messages({
        "string.base": "Cover image must be a valid string path or URL",
        "string.uri": "Cover image must be a valid URI",
    }),


    createdBy: Joi.string().optional(), // ObjectId as string
    updatedBy: Joi.string().optional(),
})