import mongoose from "mongoose";

const checkoutSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    items: [
      {
        product: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "Product",
        },

        variant: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "Variant",
        },
        quantity: { type: Number, default: 1, min: 1 },
      },
    ],
    totalAmount: {
      type: Number,
      required: [true, "Total amount is required"],
      default: 0,
    },
    discount: {
      type: Number,
      default: 0,
    },
    priceAfterDiscount: {
      type: Number,
      default: 0,
    },

    paymentMethod: {
      type: String,
      enum: ["cod", "online"],
      required: [true, "Payment method is required"],
    },
    paymentStatus: {
      type: String,
      enum: ["Pending", "Paid", "Failed", "Cancelled"],
      default: "Pending",
    },
    shippingAddress: {
      type: String,
      required: true,
    },
    district: {
      type: String,
      enum: [
        "Dhaka",
        "Gazipur",
        "Narayanganj",
        "Tangail",
        "Kishoreganj",
        "Manikganj",
        "Munshiganj",
        "Narsingdi",
        "Faridpur",
        "Rajbari",
        "Madaripur",
        "Gopalganj",
        "Shariatpur",
        "Chattogram",
        "Cox's Bazar",
        "Bandarban",
        "Khagrachhari",
        "Rangamati",
        "Feni",
        "Noakhali",
        "Lakshmipur",
        "Chandpur",
        "Brahmanbaria",
        "Cumilla",
        "Sylhet",
        "Moulvibazar",
        "Habiganj",
        "Sunamganj",
        "Khulna",
        "Bagerhat",
        "Satkhira",
        "Jessore",
        "Jhenaidah",
        "Magura",
        "Narail",
        "Kushtia",
        "Chuadanga",
        "Meherpur",
        "Barisal",
        "Bhola",
        "Patuakhali",
        "Jhalokati",
        "Pirojpur",
        "Barguna",
        "Rajshahi",
        "Natore",
        "Naogaon",
        "Chapainawabganj",
        "Pabna",
        "Sirajganj",
        "Bogura",
        "Joypurhat",
        "Rangpur",
        "Dinajpur",
        "Thakurgaon",
        "Panchagarh",
        "Kurigram",
        "Gaibandha",
        "Nilphamari",
        "Lalmonirhat",
        "Mymensingh",
        "Jamalpur",
        "Sherpur",
        "Netrokona",
      ],
      required: true,
    },
    orderStatus: {
      type: String,
      enum: ["Processing", "Delivered", "Cancelled"],
      default: "Processing",
    },
    TrxId: {
      type: String,
    },
  },
  {
    timestamps: true,
    versionKey: false,
  },
);
export const Checkout = mongoose.model("Checkout", checkoutSchema);