import Joi from "joi";

// ─────────────────────────────────────────────
// Tenant Joi Validation Schema
// ─────────────────────────────────────────────

const tenantValidationSchema = Joi.object({
  // ── Identity ──────────────────────────────
  tenantId: Joi.string()
    .guid({ version: ["uuidv4"] })
    .optional() // auto-generated by default
    .messages({
      "string.guid": "tenantId must be a valid UUID v4",
    }),

  fullName: Joi.string().min(2).max(100).required().messages({
    "string.min": "fullName must be at least 2 characters",
    "string.max": "fullName must not exceed 100 characters",
    "any.required": "fullName is required",
  }),

  // ── Business Information ───────────────────
  businessName: Joi.string().max(150).optional().messages({
    "string.max": "businessName must not exceed 150 characters",
  }),

  businessEmail: Joi.string()
    .email({ tlds: { allow: false } })
    .lowercase()
    .required()
    .messages({
      "string.email": "businessEmail must be a valid email address",
      "any.required": "businessEmail is required",
    }),

  businessPhone: Joi.string()
    .pattern(/^[+\d\s\-().]{7,20}$/)
    .optional()
    .messages({
      "string.pattern.base": "businessPhone format is invalid",
    }),

  businessWebsite: Joi.string()
    .uri({ scheme: ["http", "https"] })
    .optional()
    .messages({
      "string.uri": "businessWebsite must be a valid URL (http/https)",
    }),

  businessAddress: Joi.string().max(300).optional().messages({
    "string.max": "businessAddress must not exceed 300 characters",
  }),

  contactPageEmail: Joi.string()
    .email({ tlds: { allow: false } })
    .lowercase()
    .optional()
    .messages({
      "string.email": "contactPageEmail must be a valid email address",
    }),

  // ── Central Control ────────────────────────
  centralStatus: Joi.string()
    .valid("active", "inactive")
    .default("active")
    .optional()
    .messages({
      "any.only": "centralStatus must be either 'active' or 'inactive'",
    }),

  isVerified: Joi.boolean().default(false).optional(),

  // ── Branding ──────────────────────────
  logo: Joi.string()
    .uri({ scheme: ["http", "https"] })
    .optional()
    .messages({
      "string.uri": "logo must be a valid URL",
    }),

  favicon: Joi.string()
    .uri({ scheme: ["http", "https"] })
    .optional()
    .messages({
      "string.uri": "favicon must be a valid URL",
    }),

  invoiceLogo: Joi.string()
    .uri({ scheme: ["http", "https"] })
    .optional()
    .messages({
      "string.uri": "invoiceLogo must be a valid URL",
    }),

  // ── Social Media ───────────────────────
  socialMediaLinks: Joi.array()
    .items(
      Joi.object({
        platform: Joi.string().max(50).required().messages({
          "any.required": "platform is required in socialMediaLinks",
        }),
        url: Joi.string()
          .uri({ scheme: ["http", "https"] })
          .required()
          .messages({
            "string.uri": "url in socialMediaLinks must be a valid URL",
            "any.required": "url is required in socialMediaLinks",
          }),
      }),
    )
    .optional(),

  // ── Banking Information ────────────────────
  bankDetails: Joi.array()
    .items(
      Joi.object({
        bankName: Joi.string().max(100).optional(),
        accountName: Joi.string().max(100).optional(),
        accountNumber: Joi.string()
          .pattern(/^\d{5,20}$/)
          .optional()
          .messages({
            "string.pattern.base": "accountNumber must be 5–20 digits",
          }),
        branchName: Joi.string().max(100).optional(),
        routingNumber: Joi.string()
          .pattern(/^\d{6,15}$/)
          .optional()
          .messages({
            "string.pattern.base": "routingNumber must be 6–15 digits",
          }),
      }),
    )
    .optional(),

  // ── Website & Invoice Settings ────────────
  invoiceFooterNotes: Joi.string().max(500).optional().messages({
    "string.max": "invoiceFooterNotes must not exceed 500 characters",
  }),

  websiteFooterNotes: Joi.string().max(500).optional().messages({
    "string.max": "websiteFooterNotes must not exceed 500 characters",
  }),

  // ── SEO Settings ──────────────────────────
  seoMetaTitle: Joi.string().max(70).optional().messages({
    "string.max": "seoMetaTitle must not exceed 70 characters",
  }),

  seoMetaDescription: Joi.string().max(160).optional().messages({
    "string.max": "seoMetaDescription must not exceed 160 characters",
  }),

  seoKeywords: Joi.array().items(Joi.string().max(50)).optional().messages({
    "string.max": "Each seoKeyword must not exceed 50 characters",
  }),

  // ── Client Configuration ──────────────────
  clientType: Joi.array().items(Joi.string().max(50)).optional(),

  // ── Audit (usually set by server, not user) ─
  createdBy: Joi.string().optional(), // ObjectId as string

  updatedBy: Joi.string().optional(), // ObjectId as string
}).options({ abortEarly: false }); // show ALL errors at once

// Update schema — all field optional (partial update)
export const updateTenantSchema = tenantValidationSchema.fork(
  [
    "fullName",
    "businessEmail",
    "businessPhone",
    "businessWebsite",
    "centralStatus",
    "socialMediaLinks",
    "bankDetails",
    // ... other fields
  ],
  (field) => field.optional(),
);

// ─────────────────────────────────────────────
// Reusable validate middleware
// ─────────────────────────────────────────────
export const validateTenant = (req, res, next) => {
  const { error, value } = tenantValidationSchema.validate(req.body);
  if (error) {
    return res.status(400).json({
      success: false,
      message: "Validation failed",
      errors: error.details.reduce((acc, err) => {
        acc[err.context.key] = err.message.replace(/"/g, "");
        return acc;
      }, {}),
    });
  }
  req.body = value; // use sanitised & defaulted value
  next();
};

export default tenantValidationSchema;
